export type GenreType =
    | 'DNB'
    | 'ELECTRO'
    | 'POP'
    | 'HIPHOP'
    | 'ROCK'
    | 'JAZZ'
    | 'HYPER-POP'
    | 'DRILL'
    | 'PHONK'
    | 'TRAP'
    | 'EDM'
    | 'TECHNO'
    | 'AMBIENT'
    | 'LO-FI'
    | 'SYNTHWAVE'