export type GenreType =
    | 'hyperpop'
    | 'rock'
    | 'pop'
    | 'hiphop'
    | 'jazz'
    | 'classical'
    | 'drill'
    | 'phonk'
    | 'trap'
    | 'edm'
    | 'techno'
    | 'ambient'
    | 'lofi'
    | 'synthwave';